services:
    radarr:
        container_name: radarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
            - "7878:7878"
        environment:
            - PUID=${TF_PUID:-1000}
            - PGID=${TF_PGID:-1000}
            - TZ=${TF_TZ:-UTC}
        volumes:
            - ${TF_ROOT}/radarr/config:/config
            - ${TF_ROOT}/data:/data
            - ${TF_ROOT}/data/torrents:/data/torrents
