version: '3.8'
services:
    prowlarr:
        extends:
            file: ../xarr/prowlarr/compose.yaml
            service: prowlarr
    whisparr:
        extends:
            file: ../xarr/whisparr/compose.yaml
            service: whisparr
    sabnzbd:
        extends:
            file: ../sabnzbd/compose.yaml
            service: sabnzbd