services:
    whisparr:
        container_name: whisparr
        image: ghcr.io/hotio/whisparr:v3
        ports:
            - "6969:6969"
        environment:
            - PUID=${TF_PUID:-1000}
            - PGID=${TF_PGID:-1000}
            - TZ=${TF_TZ:-UTC}
        volumes:
            - ${TF_ROOT}/whisparr/config:/config
            - ${TF_ROOT}/data:/data
            - ${TF_ROOT}/data/torrents:/data/torrents
