services:
    sonarr:
        container_name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
            - "8989:8989"
        environment:
            - PUID=${TF_PUID:-1000}
            - PGID=${TF_PGID:-1000}
            - TZ=${TF_TZ:-UTC}
        volumes:
            - ${TF_CONFIG_DIR:-${TF_ROOT}}/sonarr/config:/config
            - ${TF_DATA_DIR:-${TF_ROOT}/data}:/data
            - ${TF_DATA_DIR:-${TF_ROOT}/data}/torrents:/data/torrents
            - ${TF_IMPORTS_DIR:-${TF_ROOT}/imports}/sonarr_tv:/imports
