services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${TF_PUID:-1000}
      - PGID=${TF_PGID:-1000}
      - TZ=${TF_TZ:-UTC}
    volumes:
      - ${TF_CONFIG_DIR:-${TF_ROOT}}/sabnzbd/config:/config
      - ${TF_DATA_DIR:-${TF_ROOT}/data}:/data
      - ${TF_DATA_DIR:-${TF_ROOT}/data}/usenet:/data/usenet
    ports:
      - 8080:8080
    restart: unless-stopped
