services:
    readarr:
      image: lscr.io/linuxserver/readarr:develop
      container_name: readarr
      environment:
          - PUID=1000
          - PGID=1000
        #   - PUID=502 # Use a User ID that has permissions on the volumes below
        #   - PGID=20 # Use a Group ID that has permissions on the volumes below
          - TZ=Asia/Bangkok
      volumes:
          - /Volumes/Pteri/torrent_fiesta/readarr/config:/config
          - /Volumes/Pteri/torrent_fiesta/data:/data
          - /Volumes/Pteri/torrent_fiesta/data/torrents:/data/torrents
      ports:
          - 8787:8787
      restart: unless-stopped
