services:
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=${TF_PUID:-1000}
            - PGID=${TF_PGID:-1000}
            - TZ=${TF_TZ:-UTC}
        volumes:
            - ${TF_CONFIG_DIR:-${TF_ROOT}}/prowlarr/config:/config
        ports:
            - 9696:9696
        restart: unless-stopped
